(define (make-point x y) (cons x y))
(define (x-point p) (car p))
(define (y-point p) (cdr p))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define (make-segment pa pb) (cons pa pb))
(define (start-segment s) (car s))
(define (end-segment s) (cdr s))

(define (midpoint-segment s)
  (let ((st (start-segment s))
	(ed (end-segment s)))
  (make-point (/ (+ (x-point st) (x-point ed)) 2)
	      (/ (+ (y-point st) (y-point ed)) 2))))

;(define st (make-point 1 1))
;(define ed (make-point 3 3))
;(print-point (midpoint-segment (make-segment st ed)))
;(newline)
